/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/atoms/Button.vue')['default']
    Card: typeof import('./src/components/atoms/Card.vue')['default']
    Carousel: typeof import('./src/components/organisms/Carousel.vue')['default']
    IconSimpleIconsFlathub: typeof import('~icons/simple-icons/flathub')['default']
    IconSimpleIconsGithub: typeof import('~icons/simple-icons/github')['default']
    IconSimpleIconsGitlab: typeof import('~icons/simple-icons/gitlab')['default']
    IconSimpleIconsKde: typeof import('~icons/simple-icons/kde')['default']
    ServiceCard: typeof import('./src/components/molecules/ServiceCard.vue')['default']
  }
}
